twig:
    file_name_pattern: '*.twig'
    form_themes:
        - 'bootstrap_3_layout.html.twig'
        - '@InfiniteForm/collection_table_theme.html.twig'
        - '@InfiniteForm/form_theme.html.twig'
        - 'form_theme.html.twig'

when@test:
    twig:
        strict_variables: true
